apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubeedge-project
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: kubeedge-app
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'