apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubeedge-daemonset
spec:
  selector:
      matchLabels:
        name: kubeedge-daemonset
  template:
    metadata:
      labels:
        name: kubeedge-daemonset 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/edge
                  operator: DoesNotExist
                - key: node-role.kubernetes.io/agent
                  operator: DoesNotExist 
      containers:
       - name: httpd
         image: httpd
