apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http-daemonset
spec:
  selector:
      matchLabels:
        name: http-daemonset
  template:
    metadata:
      labels:
        name: http-daemonset 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/edge
                  operator: Exists
                - key: node-role.kubernetes.io/agent
                  operator: Exists  
      containers:
       - name: httpd
         image: httpd
